name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Provision .NET 10 Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Compile and Publish Blazor WebAssembly
        run: dotnet publish -c Release -o release --nologo

      - name: Bypass GitHub Pages Jekyll Processing
        run: touch release/wwwroot/.nojekyll

      - name: Upload WebAssembly Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'release/wwwroot'

      - name: Execute Deployment
        id: deployment
        uses: actions/deploy-pages@v4